const { Client, MessageMedia, LocalAuth } = require('whatsapp-web.js')
const qrcode = require('qrcode-terminal')
const axios = require('axios')
const FormData = require('form-data');
const fs = require('fs');
const { Blob } = require('node:buffer');
const { downloadMessageMedia } = require('./utils/storage');

require('dotenv').config()

const client = new Client({
    authStrategy: new LocalAuth()
})

client.on('qr', qr => {
    qrcode.generate(qr, {small: true})
});

client.on('authenticated', (session) => console.log(`Autenticado`))

client.on('ready', () => console.log('O zap-gpt está pronto 😋 Não esquece da estrelinha no repo ⭐ by: Victor Harry 🧙‍'))

client.on('message_create', message => commands(message))

client.initialize();


const headers = {
    'Authorization': `Bearer ${process.env.OPENAI_KEY}`,
    'Content-Type': 'application/json'
}

const axiosInstance = axios.create({
    baseURL: 'https://api.openai.com/',
    timeout: 120000,
    headers: headers
});

const getDavinciResponse = async (clientText) => {
    const body = {
        "model": "text-davinci-003",
        "prompt": clientText,
        "max_tokens": 2048,
        "temperature": 1
    }

    try {
        const { data } = await axiosInstance.post('v1/completions', body)
        const botAnswer = data.choices[0].text
        // return `ChatGPT 🤖 ${botAnswer}`
        return `🤖 ${botAnswer}`
    } catch (e) {
        console.log(e);
        return `❌ OpenAI Response Error`
    }
}

const getDalleResponse = async (clientText) => {
    const body = {
        prompt: clientText, // Descrição da imagem
        n: 1, // Número de imagens a serem geradas
        size: "256x256", // Tamanho da imagem
    }

    try {
        const { data } = await axiosInstance.post('v1/images/generations', body)
        return data.data[0].url
    } catch (e) {
        console.log(e);
        return `❌ OpenAI Response Error`
    }
}

const getWhisperResponse = async (mp3Path, message) => {
    const formData = new FormData();

    formData.append('model', 'whisper-1');
    let mp3File = fs.createReadStream(mp3Path);
    formData.append('file', mp3File, 'input.mp3');

    try {
        const { data } = await axiosInstance.post(
            'v1/audio/transcriptions',
            formData,
            { headers: {"Content-Type": "multipart/form-data" }
        })
        return data.text;
        // return data.data[0].url
    } catch (e) {
        console.log(e);
        return `❌ OpenAI Whisper Response Error`
    }
}

const commands = async (message) => {
    const iaCommands = {
        davinci3: "/bot",
        dalle: "/img",
        whisper: "/whisper"
    }
    let firstWord = message.body.substring(0, message.body.indexOf(" "))
    const isAudio = message.type == 'ptt' && message._data.mimetype === 'audio/ogg; codecs=opus'
    if (isAudio) {
        firstWord = '/whisper'
    }
   /*
    * Faremos uma validação no message.from
    * para caso a gente envie um comando
    * a response não seja enviada para
    * nosso próprio número e sim para 
    * a pessoa ou grupo para o qual eu enviei
    */
    const sender = message.from.includes(process.env.PHONE_NUMBER) ? message.to : message.from
    switch (firstWord) {
        case iaCommands.davinci3:
            const question = message.body.substring(message.body.indexOf(" "));
            getDavinciResponse(question).then(async (response) => {
                const contact = await message.getContact()
                client.sendMessage(sender, `${response}\n\n_Generated by @${contact.id.user}_`, { mentions: [contact] })
            })
            break

        case iaCommands.dalle:
            const imgDescription = message.body.substring(message.body.indexOf(" "));
            const contact = await message.getContact();
            getDalleResponse(imgDescription, message).then(async (imgUrl)  => {
                const media = await MessageMedia.fromUrl(imgUrl)
                // Caso queira mandar como Sticker, acrescente em options -> sendMediaAsSticker: true
                const options = {
                    mentions: [contact], 
                    caption: `_Generated by @${contact.id.user}_`, 
                    media: media,
                    sendMediaAsSticker: true,
                }
                await client.sendMessage(sender, media, options)
            })
            break
        case iaCommands.whisper:
            const mp3Path = await downloadMessageMedia(message);

            getWhisperResponse(mp3Path, message).then(async (response) => {
                // const contact = await message.getContact()
                message.reply(`🤖 ${response}`)
                // client.sendMessage(sender, `🤖${response}\n\_Transcrito by @${contact.id.user}_`, { mentions: [contact] })

                getDavinciResponse(`${response}`).then(async (summary) => {
                    // const contact = await message.getContact()
                
                    // message.reply(sender, `${summary}`)
                    message.reply(summary)
                    // client.sendMessage(sender, `${summary}\n_Resumo by @${contact.id.user}_`, { mentions: [contact] })
                })
            })
    }
}
